import Form from "@/components/Form";

export const metadata = {
  title: "Contact - Blog Mockup",
  description: "Generated by create next app",
};

function Contact() {
  return (
    <div>
      <br />
      <h2 className="text-4xl m-10 font-bold text-center ">Contact</h2>
      <section>
        <Form />
      </section>
    </div>
  );
}

export default Contact;
