import ProductsWidget from "@/components/ProductsWidget";

export const metadata = {
  title: "Products & Frebbies - Blog Mockup",
  description: "Generated by create next app",
};

function Page() {
  return (
    <div>
      <br />
      <h1 className="text-4xl m-10 font-bold text-center">
        Products & Frebbies
      </h1>
      <section>
        <ProductsWidget />
      </section>
    </div>
  );
}

export default Page;
